### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by ArnaKuzy** [shuchkin/simplecsv#1]
Hello php 7.49 trigger this errors

Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\shuchkin\simplecsv\src\SimpleCSV.php on line 102

Deprecated: Array and string offset access syntax with curly braces is deprecated in ...\shuchkin\simplecsv\src\SimpleCSV.php on line 103

**Comment by shuchkin** [comment]
try 0.1.1

**Comment by ArnaKuzy** [comment]
It work thx
