### ISSUE TITLE
How to handle latin characters?

### ISSUE THREAD

**Issue by jonanthonii** [shuchkin/simplecsv#8]
I use simplexlsx but decided to switch over to simplecsv because i am aiming for efficient reading and importing into mysql database.

I have no idea how to handle latin chars. (one of the errors look like this: Incorrect string value: '\xD1AQUE ...')

I have tried using charset utf8mb4 but still does not work.

**Comment by shuchkin** [comment]
1) detect CSV file charset
2) see https://dev.mysql.com/doc/refman/8.4/en/charset-connection.html

```php
$csv_charset = 'ANSI-1251';
foreach ($csv->rows() as $r) {
    $subject = mb_convert_encoding( $r[1], 'UTF-8', $csv_charset);
    $sql = "INSERT INTO news SET subject='" . $db->escape( $subject ) . "'";
}
```

**Comment by jonanthonii** [comment]
> 1. detect CSV file charset
> 2. see https://dev.mysql.com/doc/refman/8.4/en/charset-connection.html
> 
> ```
> $csv_charset = 'ANSI-1251';
> foreach ($csv->rows() as $r) {
>     $subject = mb_convert_encoding( $r[1], 'UTF-8', $csv_charset);
>     $sql = "INSERT INTO news SET subject='" . $db->escape( $subject ) . "'";
> }
> ```

I was able to identify my csv file charset which is UTF-8.

Thanks to the code you provided  revised it a lil bit and now it's working perfectly!

    foreach($csv->rows() as $row){
        $customer_address = mb_convert_encoding(nospace(str_replace("'", "\'", $row[6])), 'UTF-8', 'UTF-8');
        $sql = "INSERT INTO transaction SET address='" . $conn->real_escape_string($customer_address) . "'";
     }
